const { expect } = require('chai');
const jsonTraverse = require('json-schema-traverse');

const {
  createVscodeSchema,
  traverseSchemaRemoveAutoGenerated,
  traverseSchemaAddBareWorkflowDescription,
  traverseSchemaAddMarkdownDescription,
  traverseSchemaAddPatternErrorDescription,
} = require('../schema-expo-xdl');

describe('createVscodeSchema', () => {
  // Snapshot testing to make sure nothing changed unexpectedly
  [39, 41, 45].forEach((sdkVersion) => {
    it(`creates expected SDK ${sdkVersion} schema`, () => {
      const xdlRespnse = require(`./__fixtures__/expo-xdl-${sdkVersion}.json`);
      const xdlSchema = xdlRespnse.data.schema; // the full response from exp.host
      const schema = createVscodeSchema(`${sdkVersion}.0.0`, xdlSchema);
      expect(schema).toMatchSnapshot();
    });
  });

  it('returns schema wrapped with optional `expo` property', () => {
    const xdlSchema = { description: 'All properties' };
    const schema = createVscodeSchema('0.0.0', xdlSchema);
    expect(schema.oneOf).to.satisfy((items) =>
      items.some((item) => item.$ref && typeof item.$ref === 'string')
    );
    expect(schema.oneOf).to.satisfy((items) =>
      items.some(
        (item) => item.type === 'object' && item.required && item.required.includes('expo')
      )
    );
  });

  it('moves xdl definitions to root definitions', () => {
    const definitions = { android: { type: 'string' }, ios: { type: 'string' } };
    const xdlSchema = { description: 'All properties', definitions };
    const schema = createVscodeSchema('0.0.0', xdlSchema);
    expect(schema.definitions).to.equal(definitions);
    expect(schema.definitions.VscodeExpoXdl).not.to.have.property('definitions');
  });

  it('adds bare workflow description to markdownDescription', () => {
    const xdlSchema = { description: 'All properties' };
    const schema = createVscodeSchema('0.0.0', xdlSchema);
    expect(schema.definitions.VscodeExpoXdl).to.have.property('description');
    expect(schema.definitions.VscodeExpoXdl).to.have.property('markdownDescription');
  });

  it('does not add auto-generated nested properties', () => {
    const xdlSchema = {
      description: 'All properties',
      properties: {
        normal: { type: 'string' },
        hidden: { type: 'string', meta: { autogenerated: true } },
      },
    };
    const schema = createVscodeSchema('0.0.0', xdlSchema);
    expect(schema.definitions.VscodeExpoXdl.properties).to.have.property('normal');
    expect(schema.definitions.VscodeExpoXdl.properties).not.to.have.property('hidden');
  });
});

// Some usefull stubs to quickly create test schemas
const description = 'Some property';
const markdownDescription = 'Rich description';
const bareWorkflow = 'Only available in bare';
const autogenerated = true;

/** A test version of `createVscodeSchema` to keep using the same API for jsonTraverse */
function testTraverse(schema, method) {
  jsonTraverse(
    schema,
    (nested, _nestedPath, _root, _parentPath, parentKey, parent, parentKeyIndex) => {
      method(nested, parent, parentKey, parentKeyIndex);
    }
  );
}

describe('traverseSchemaRemoveAutoGenerated', () => {
  it('skips autogenerated parents', () => {
    const schema = { description, meta: { autogenerated } };
    testTraverse(schema, traverseSchemaRemoveAutoGenerated);
    expect(Object.keys(schema)).to.have.length(2);
    expect(schema).to.containSubset({ description, meta: { autogenerated } });
  });

  it('skips non-autogenerated child property', () => {
    const child = { type: 'string' };
    const parent = { description, properties: { child } };
    testTraverse(parent, traverseSchemaRemoveAutoGenerated);
    expect(parent.properties.child).to.contain(child);
  });

  it('removed autogenerated child property', () => {
    const child = { type: 'string', meta: { autogenerated } };
    const parent = { description, properties: { child } };
    testTraverse(parent, traverseSchemaRemoveAutoGenerated);
    expect(parent.properties).not.to.have.property('child');
  });
});

describe('traverseSchemaAddBareWorkflowDescription', () => {
  const PREFIX = '\n\n**Bare workflow** - ';

  it('skips when meta.bareWorkflow does not exist', () => {
    const schema = { description };
    testTraverse(schema, traverseSchemaAddBareWorkflowDescription);
    expect(Object.keys(schema)).to.have.length(1);
    expect(schema.description).to.equal(description);
  });

  it('prepends meta.bareWorkflow with prefix to description', () => {
    const schema = { description, meta: { bareWorkflow } };
    testTraverse(schema, traverseSchemaAddBareWorkflowDescription);
    expect(schema.description).to.equal(`${description}${PREFIX}${bareWorkflow}`);
  });

  it('sets meta.bareWorkflow with prefix as description when not defined', () => {
    const schema = { meta: { bareWorkflow } };
    testTraverse(schema, traverseSchemaAddBareWorkflowDescription);
    expect(schema.description).to.equal(`${PREFIX}${bareWorkflow}`.trim()); // Trim should remove the two newlines
  });
});

describe('traverseSchemaAddMarkdownDescription', () => {
  it('skips when markdownDescription exists', () => {
    const schema = { description, markdownDescription };
    testTraverse(schema, traverseSchemaAddMarkdownDescription);
    expect(Object.keys(schema)).to.have.length(2);
  });

  it('skips when description does not exist', () => {
    const schema = { type: 'string' };
    testTraverse(schema, traverseSchemaAddMarkdownDescription);
    expect(schema).to.contain({ type: 'string' });
  });

  it('copies the description to markdownDescription', () => {
    const schema = { description };
    testTraverse(schema, traverseSchemaAddMarkdownDescription);
    expect(schema).to.have.property('markdownDescription', description);
  });
});

describe('traverseSchemaAddPatternErrorDescription', () => {
  it('skips when pattern is not set', () => {
    const schema = { description };
    testTraverse(schema, traverseSchemaAddPatternErrorDescription);
    expect(Object.keys(schema)).to.have.length(1);
  });

  it('skips when meta.regexHuman is not set', () => {
    const schema = { description, pattern: '^image/png$' };
    testTraverse(schema, traverseSchemaAddPatternErrorDescription);
    expect(Object.keys(schema)).to.have.length(2);
  });

  it('copies the meta.regexHuman to patternErrorMessage', () => {
    const schema = { description, pattern: '^image/png$', meta: { regexHuman: 'Better message' } };
    testTraverse(schema, traverseSchemaAddPatternErrorDescription);
    expect(schema.patternErrorMessage).to.equal(schema.meta.regexHuman);
  });
});
