name: Setup project
description: Prepare the project for any CI action

inputs:
  node-version:
    description: Version of Node to install
    default: 16.x

  with-fixture:
    description: If the setup should install the test/fixture files
    type: boolean
  
  without-cache:
    description: If the Yarn cache should not be used
    type: boolean

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node with cache
      if: ${{ inputs.without-cache != 'true' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
        cache-dependency-path: |
          yarn.lock
          test/fixture/yarn.lock

    - name: 🏗 Setup Node without cache
      if: ${{ inputs.without-cache == 'true' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: 📦 Install fixture
      if: ${{ inputs.with-fixture == 'true' }}
      run: yarn install --frozen-lockfile
      working-directory: test/fixture
      shell: bash
