name: Setup project
description: Prepare the project for any CI action

inputs:
  bun-version:
    description: Version of Bun to install
    default: 1.x

  node-version:
    description: Version of Node to install
    default: 18.x

  with-fixture:
    description: If the setup should install the test/fixture files
    type: boolean

  without-cache:
    description: If the Node package cache should not be used
    type: boolean

runs:
  using: composite
  steps:
    - name: 🏗 Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: 🏗 Setup Node without cache
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: 📦 Install dependencies
      run: bun install --frozen-lockfile
      shell: bash

    - name: 📦 Install fixture
      if: ${{ inputs.with-fixture == 'true' }}
      run: bun install --frozen-lockfile
      working-directory: test/fixture
      shell: bash
