name: Setup project
description: Prepare the project for any CI action

inputs:
  node-version:
    description: Version of Node to install
    default: 20.x

  with-fixture:
    description: If the setup should install the test/fixture files
    default: "false"

  without-cache:
    description: If the Node package cache should not be used
    default: "false"

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node with cache
      if: ${{ inputs.without-cache != 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: |
          package-lock.json
          test/fixture/package-lock.json

    - name: 🏗 Setup Node without cache
      if: ${{ inputs.without-cache == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: 📦 Install dependencies
      run: npm ci
      shell: bash

    - name: 📦 Install fixture
      if: ${{ inputs.with-fixture == 'true' }}
      run: npm ci
      working-directory: test/fixture
      shell: bash
