name: Setup VS Code Headless
description: Prepare the environment to run VS Code headless tests

inputs:
  command:
    description: The test command to execute
    required: true

runs:
  using: composite
  steps:
    - name: ðŸ— Setup Linux xvfb
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install -y xvfb x11-xserver-utils
      shell: bash

    - name: ðŸ–¥ï¸ Start Linux xvfb
      if: ${{ runner.os == 'Linux' }}
      run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Started xvfb"
      shell: bash

    - name: ðŸ‘· Configure Linux display
      if: ${{ runner.os == 'Linux' }}
      run: echo "DISPLAY=:99.0" >> $GITHUB_ENV
      shell: bash
