name: Test VS Code
description: Run the integration tests within VS Code

inputs:
  command:
    description: The test command to execute with xvfb-run
    required: true

runs:
  using: composite
  steps:
    - name: 🧪 Test on Linux
      if: ${{ runner.os == 'Linux' }}
      # Unset wrong Electron setting,
      # see: https://github.com/microsoft/vscode-test/issues/127
      run: |
        unset DBUS_SESSION_BUS_ADDRESS
        xvfb-run -a ${{ inputs.command }}
      shell: bash

    - name: 🧪 Test on MacOS/Windows
      if: ${{ runner.os != 'Linux' }}
      run: ${{ inputs.command }}
      shell: bash
